services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        value: victusxgod
      - key: OWNER_URL
        value: https://t.me/victus_xd
      - key: OWNER_ID_1
        sync: false
      - key: OWNER_ID_2
        sync: false
      - key: WORKERS
        value: 16
